apiVersion: v1
kind: Service
metadata:
  name: api-gateway-company-service
  namespace: selectgearmotors-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Para Network Load Balancer (opcional)
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true" # Para um Load Balancer interno (opcional)
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9944
      targetPort: 9944
  selector:
    app: selectgearmotors-company-api