apiVersion: v1
kind: Service
metadata:
  name: api-gateway-company-service
  namespace: selectgearmotors-ns
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9924
      targetPort: 9924
  selector:
    app: selectgearmotors-company-api